'use client';
import { useEffect, useRef, useState } from 'react';

const scenes = [
 {label:'Received an instruction',icon:'→',jp:'これ終わったら、先に仕込みお願い。',en:'After finishing this, please do the preparation first.',romaji:'Kore owattara, saki ni shikomi onegai.',phrase:'はい、これが終わったら、先に仕込みをします。',phraseR:'Hai, kore ga owattara, saki ni shikomi o shimasu.',meaning:'Yes, after finishing this, I’ll do the preparation first.',context:'Your manager is changing your task priority. Repeat the order back to confirm it.'},
 {label:"Didn't understand",icon:'？',jp:'冷蔵庫から二つ出して、こっちに持ってきて。',en:'Take two from the refrigerator and bring them here.',romaji:'Reizōko kara futatsu dashite, kocchi ni motte kite.',phrase:'冷蔵庫から二つですね。',phraseR:'Reizōko kara futatsu desu ne.',meaning:'Two from the refrigerator, correct?',context:'Repeating the important detail is a natural, professional way to confirm an instruction.'},
 {label:'Something is running out',icon:'！',jp:'チキンがもうすぐなくなります。',en:'The chicken is almost finished.',romaji:'Chikin ga mōsugu nakunarimasu.',phrase:'チキンを補充してもいいですか？',phraseR:'Chikin o hojū shite mo ii desu ka?',meaning:'May I restock the chicken?',context:'Report shortages before they become urgent, then suggest the next action.'}
];
const vocabulary = [
 [{jp:'終わったら',reading:'owattara',en:'after finishing'},{jp:'先に',reading:'saki ni',en:'first / before'},{jp:'仕込み',reading:'shikomi',en:'preparation'}],
 [{jp:'冷蔵庫',reading:'reizōko',en:'refrigerator'},{jp:'二つ',reading:'futatsu',en:'two items'},{jp:'持ってきて',reading:'motte kite',en:'bring it here'}],
 [{jp:'もうすぐ',reading:'mōsugu',en:'soon / almost'},{jp:'なくなります',reading:'nakunarimasu',en:'will run out'},{jp:'補充',reading:'hojū',en:'restock'}]
];
export default function Home(){
 const [selected,setSelected]=useState(1), [input,setInput]=useState(scenes[1].jp), [output,setOutput]=useState(scenes[1].en), [show,setShow]=useState(true), [loading,setLoading]=useState(false), [listening,setListening]=useState(false), [saved,setSaved]=useState(3), [now,setNow]=useState(''), [error,setError]=useState(''), [graph,setGraph]=useState<string[]|null>(null), [flipped,setFlipped]=useState<number|null>(null), [savedCards,setSavedCards]=useState<string[]>([]), [mission,setMission]=useState('');
 const audioContext=useRef<AudioContext|null>(null), processor=useRef<ScriptProcessorNode|null>(null), micStream=useRef<MediaStream|null>(null), samples=useRef<Float32Array[]>([]);
 const active=scenes[selected];
 useEffect(()=>{const tick=()=>setNow(new Intl.DateTimeFormat('en',{hour:'2-digit',minute:'2-digit'}).format(new Date()));tick();const t=setInterval(tick,30000);return()=>clearInterval(t)},[]);
 function choose(i:number){setSelected(i);setInput(scenes[i].jp);setOutput(scenes[i].en);setError('');setGraph(null);setFlipped(null);setSavedCards([]);setMission('');setShow(true)}
 async function translate(text=input){if(!text.trim())return;setShow(false);setLoading(true);setError('');try{const response=await fetch('/api/translate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});const data=await response.json();if(!response.ok)throw new Error(data.error);setOutput(data.translation);setShow(true)}catch(e:any){setOutput(active.en);setShow(true);setError(e.message==='SHISA API key is not configured'?'Demo mode — add SHISA key for live translation':e.message)}finally{setLoading(false)}}
 function wavBlob(parts:Float32Array[],rate:number){const length=parts.reduce((n,p)=>n+p.length,0),buffer=new ArrayBuffer(44+length*2),view=new DataView(buffer);const write=(o:number,s:string)=>[...s].forEach((c,i)=>view.setUint8(o+i,c.charCodeAt(0)));write(0,'RIFF');view.setUint32(4,36+length*2,true);write(8,'WAVE');write(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,rate,true);view.setUint32(28,rate*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);write(36,'data');view.setUint32(40,length*2,true);let offset=44;for(const part of parts)for(const value of part){const s=Math.max(-1,Math.min(1,value));view.setInt16(offset,s<0?s*32768:s*32767,true);offset+=2}return new Blob([buffer],{type:'audio/wav'})}
 async function finishRecording(){const context=audioContext.current;if(!context)return;processor.current?.disconnect();micStream.current?.getTracks().forEach(t=>t.stop());const blob=wavBlob(samples.current,context.sampleRate);await context.close();audioContext.current=null;setListening(false);setLoading(true);try{const form=new FormData();form.append('audio',blob,'speech.wav');const response=await fetch('/api/transcribe',{method:'POST',body:form});const data=await response.json();if(!response.ok)throw new Error(data.error);setInput(data.text);await translate(data.text)}catch(e:any){setError(e.message||'Speech recognition failed');setLoading(false)}}
 async function listen(){if(listening){await finishRecording();return}try{setError('');const stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true}});const context=new AudioContext();const source=context.createMediaStreamSource(stream);const node=context.createScriptProcessor(4096,1,1);samples.current=[];node.onaudioprocess=e=>samples.current.push(new Float32Array(e.inputBuffer.getChannelData(0)));source.connect(node);node.connect(context.destination);audioContext.current=context;processor.current=node;micStream.current=stream;setListening(true)}catch{setError('Microphone permission is required')}}
 async function speak(){setError('');try{const response=await fetch('/api/speak',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:active.phrase})});if(!response.ok){const data=await response.json();throw new Error(data.error)}const url=URL.createObjectURL(await response.blob());const audio=new Audio(url);audio.onended=()=>URL.revokeObjectURL(url);await audio.play()}catch(e:any){if('speechSynthesis' in window){speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(active.phrase);utterance.lang='ja-JP';utterance.rate=.85;speechSynthesis.speak(utterance);setError('Using device voice — SHISA voice temporarily unavailable')}else setError(e.message||'Voice playback unavailable')}}
 async function savePhrase(){setError('');try{const response=await fetch('/api/graph',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phrase:active.phrase,reading:active.phraseR,meaning:active.meaning,situation:active.label})});const data=await response.json();if(!response.ok)throw new Error(data.error);setSaved(saved+1);setGraph(data.nodes)}catch(e:any){setError(e.message||'Could not save to learning graph')}}
 async function saveCard(card:{jp:string,reading:string,en:string}){setError('');try{const response=await fetch('/api/graph',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'flashcard',phrase:card.jp,reading:card.reading,meaning:card.en,situation:active.label})});const data=await response.json();if(!response.ok)throw new Error(data.error);setSavedCards([...savedCards,card.jp]);setSaved(saved+1);setGraph(data.nodes)}catch(e:any){setError(e.message||'Could not save flashcard')}}
 return <main>
  <nav><div className="brand"><span className="brandMark">日</span><span>Nihongo <b>Lens</b></span><em>LIVE</em></div><div className="mainTabs"><b>Today</b><span>Situations</span><span>Practice</span><span>Progress</span></div><div className="navRight"><span className="dot"/>Tokyo · {now}<button className="saved">Learned <strong>{saved}</strong></button></div></nav>
  <section className="hero"><div className="eyebrow">JAPANESE FOR YOUR NEXT SHIFT</div><h1>Understand it.<br/><i>Use it at work.</i></h1><p>One real situation. Five minutes of practice. One mission for your next shift.</p><div className="cycle">{['See it','Understand it','Say it','Use it','Review it'].map((step,i)=><span key={step}><b>{i+1}</b>{step}</span>)}</div></section>
  <section className="workspace"><div className="scenarioBar"><span>WHAT HAPPENED AT WORK?</span><div>{scenes.map((s,i)=><button key={s.label} onClick={()=>choose(i)} className={selected===i?'active':''}><b>{s.icon}</b>{s.label}</button>)}</div></div>
   <div className="panels"><article className="inputPanel"><header><div><span>1</span><small>SEE — What did you hear?</small></div><span className="secure">● SHISA SPEECH API</span></header><textarea aria-label="Japanese to translate" value={input} onChange={e=>setInput(e.target.value)} placeholder="Record what your coworker said…"/><div className="reading">{listening?'Recording — tap Stop when finished':show?active.romaji:'Understanding Japanese…'}</div><footer><button className={`mic ${listening?'recording':''}`} onClick={listen}><span>{listening?'■':'●'}</span>{listening?'Stop & transcribe':'Record Japanese'}</button><button className="translate" onClick={()=>translate()}>Understand <span>→</span></button></footer></article>
   <article className="outputPanel"><header><div><span>2</span><small>UNDERSTAND — Meaning & intention</small></div><span className="powered">POWERED BY <b>SHISA.AI</b></span></header>{loading?<div className="thinking"><span/><span/><span/> Understanding context…</div>:show&&<><p className="translationText">{output}</p><div className="context"><span>◎</span><div><b>Workplace intention</b><p>{active.context}</p></div></div></>}</article></div>
   {error&&<div className="errorBanner">{error}</div>}
   {show&&!loading&&<aside className="learnCard"><div className="learnLabel"><span>声に出す</span><small>3 — SAY & COPY</small></div><div className="phrase"><strong>{active.phrase}</strong><span>{active.phraseR}</span></div><p>{active.meaning}</p><div className="learnActions"><button onClick={speak}>▶ Listen</button><button onClick={savePhrase}>＋ Remember</button></div></aside>}
   {graph&&<aside className="graphCard"><div><b>KNOWLEDGE GRAPH UPDATED</b><span>Powered by Neo4j</span></div><div className="graphFlow">{graph.map((node,i)=><span key={node}>{i>0&&<i>—</i>}<b className={`node n${i}`}>{node}</b></span>)}</div></aside>}
   {show&&!loading&&<section className="missionCard"><div><small>4 — USE IT</small><b>Today’s Shift Mission</b><p>Use or confirm this phrase once during your next shift.</p><em>Practice only before work, after work, or during a safe break.</em></div><div className="missionChoices">{['I used it','I forgot','It was difficult'].map(x=><button className={mission===x?'active':''} onClick={()=>setMission(x)} key={x}>{x}</button>)}</div>{mission&&<aside><b>{mission==='I used it'?'Great—review it again in 3 days.':'Try this shorter version next time:'}</b><span>{mission==='I used it'?active.phrase:'すみません、もう一度お願いします。'}</span></aside>}</section>}
   {show&&!loading&&<section className="flashSection"><header><div><span>復習</span><div><b>2-Minute Shift Review</b><small>Tap a card, recall the meaning, then save it</small></div></div><em>5 — REVIEW · {vocabulary[selected].length} WORDS</em></header><div className="flashGrid">{vocabulary[selected].map((card,i)=>{const isFlipped=flipped===i,isSaved=savedCards.includes(card.jp);return <article key={card.jp} className={`flashCard ${isFlipped?'flipped':''}`} onClick={()=>setFlipped(isFlipped?null:i)}><div className="cardTop"><span>{i+1}</span><small>{isFlipped?'ENGLISH':'RECALL FIRST'}</small></div><div className="cardWord"><strong>{isFlipped?card.en:card.jp}</strong><span>{isFlipped?'Meaning':card.reading}</span></div><button disabled={isSaved} onClick={e=>{e.stopPropagation();saveCard(card)}}>{isSaved?'✓ Scheduled in Neo4j':'＋ Add to review'}</button></article>})}</div></section>}
  </section><footer className="pageFooter"><span>Built for foreign workers in Japan</span><span>Real situation → short practice → shift mission → feedback → review</span></footer>
 </main>
}
