'use client';
import { useEffect, useRef, useState } from 'react';

const scenes = [
 {label:'At the clinic',icon:'＋',jp:'いつからこの症状がありますか？保険証をお持ちですか？',en:'When did these symptoms start? Do you have your health insurance card?',romaji:'Itsu kara kono shōjō ga arimasu ka? Hokenshō o omochi desu ka?',phrase:'保険証を持っています',phraseR:'Hokenshō o motte imasu',meaning:'I have my health insurance card.',context:'Japanese clinics usually ask for your insurance card before the consultation.'},
 {label:'City hall',icon:'〒',jp:'こちらの用紙に住所と在留カード番号をご記入ください。',en:'Please write your address and residence card number on this form.',romaji:'Kochira no yōshi ni jūsho to zairyū kādo bangō o gokinyū kudasai.',phrase:'どこに書けばいいですか？',phraseR:'Doko ni kakeba ii desu ka?',meaning:'Where should I write it?',context:'ご記入ください is a polite, formal phrase commonly used on official forms.'},
 {label:'Restaurant',icon:'箸',jp:'こちらは卵が入っていますが、アレルギーは大丈夫ですか？',en:'This contains egg. Is that okay with your allergies?',romaji:'Kochira wa tamago ga haitte imasu ga, arerugī wa daijōbu desu ka?',phrase:'卵は食べられません',phraseR:'Tamago wa taberaremasen',meaning:'I cannot eat eggs.',context:'食べられません clearly communicates a dietary restriction, not merely a preference.'}
];
const vocabulary = [
 [{jp:'症状',reading:'shōjō',en:'symptoms'},{jp:'保険証',reading:'hokenshō',en:'health insurance card'},{jp:'受付',reading:'uketsuke',en:'reception desk'}],
 [{jp:'住所',reading:'jūsho',en:'address'},{jp:'在留カード',reading:'zairyū kādo',en:'residence card'},{jp:'記入',reading:'kinyū',en:'fill in / write'}],
 [{jp:'卵',reading:'tamago',en:'egg'},{jp:'アレルギー',reading:'arerugī',en:'allergy'},{jp:'食べられません',reading:'taberaremasen',en:'cannot eat'}]
];
export default function Home(){
 const [selected,setSelected]=useState(1), [input,setInput]=useState(scenes[1].jp), [output,setOutput]=useState(scenes[1].en), [show,setShow]=useState(true), [loading,setLoading]=useState(false), [listening,setListening]=useState(false), [saved,setSaved]=useState(3), [now,setNow]=useState(''), [error,setError]=useState(''), [graph,setGraph]=useState<string[]|null>(null), [flipped,setFlipped]=useState<number|null>(null), [savedCards,setSavedCards]=useState<string[]>([]);
 const audioContext=useRef<AudioContext|null>(null), processor=useRef<ScriptProcessorNode|null>(null), micStream=useRef<MediaStream|null>(null), samples=useRef<Float32Array[]>([]);
 const active=scenes[selected];
 useEffect(()=>{const tick=()=>setNow(new Intl.DateTimeFormat('en',{hour:'2-digit',minute:'2-digit'}).format(new Date()));tick();const t=setInterval(tick,30000);return()=>clearInterval(t)},[]);
 function choose(i:number){setSelected(i);setInput(scenes[i].jp);setOutput(scenes[i].en);setError('');setGraph(null);setFlipped(null);setSavedCards([]);setShow(true)}
 async function translate(text=input){if(!text.trim())return;setShow(false);setLoading(true);setError('');try{const response=await fetch('/api/translate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});const data=await response.json();if(!response.ok)throw new Error(data.error);setOutput(data.translation);setShow(true)}catch(e:any){setOutput(active.en);setShow(true);setError(e.message==='SHISA API key is not configured'?'Demo mode — add SHISA key for live translation':e.message)}finally{setLoading(false)}}
 function wavBlob(parts:Float32Array[],rate:number){const length=parts.reduce((n,p)=>n+p.length,0),buffer=new ArrayBuffer(44+length*2),view=new DataView(buffer);const write=(o:number,s:string)=>[...s].forEach((c,i)=>view.setUint8(o+i,c.charCodeAt(0)));write(0,'RIFF');view.setUint32(4,36+length*2,true);write(8,'WAVE');write(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,rate,true);view.setUint32(28,rate*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);write(36,'data');view.setUint32(40,length*2,true);let offset=44;for(const part of parts)for(const value of part){const s=Math.max(-1,Math.min(1,value));view.setInt16(offset,s<0?s*32768:s*32767,true);offset+=2}return new Blob([buffer],{type:'audio/wav'})}
 async function finishRecording(){const context=audioContext.current;if(!context)return;processor.current?.disconnect();micStream.current?.getTracks().forEach(t=>t.stop());const blob=wavBlob(samples.current,context.sampleRate);await context.close();audioContext.current=null;setListening(false);setLoading(true);try{const form=new FormData();form.append('audio',blob,'speech.wav');const response=await fetch('/api/transcribe',{method:'POST',body:form});const data=await response.json();if(!response.ok)throw new Error(data.error);setInput(data.text);await translate(data.text)}catch(e:any){setError(e.message||'Speech recognition failed');setLoading(false)}}
 async function listen(){if(listening){await finishRecording();return}try{setError('');const stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true}});const context=new AudioContext();const source=context.createMediaStreamSource(stream);const node=context.createScriptProcessor(4096,1,1);samples.current=[];node.onaudioprocess=e=>samples.current.push(new Float32Array(e.inputBuffer.getChannelData(0)));source.connect(node);node.connect(context.destination);audioContext.current=context;processor.current=node;micStream.current=stream;setListening(true)}catch{setError('Microphone permission is required')}}
 async function speak(){setError('');try{const response=await fetch('/api/speak',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:active.phrase})});if(!response.ok){const data=await response.json();throw new Error(data.error)}const url=URL.createObjectURL(await response.blob());const audio=new Audio(url);audio.onended=()=>URL.revokeObjectURL(url);await audio.play()}catch(e:any){setError(e.message==='SHISA API key is not configured'?'Demo mode — add SHISA key for voice playback':e.message)}}
 async function savePhrase(){setError('');try{const response=await fetch('/api/graph',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phrase:active.phrase,reading:active.phraseR,meaning:active.meaning,situation:active.label})});const data=await response.json();if(!response.ok)throw new Error(data.error);setSaved(saved+1);setGraph(data.nodes)}catch(e:any){setError(e.message||'Could not save to learning graph')}}
 async function saveCard(card:{jp:string,reading:string,en:string}){setError('');try{const response=await fetch('/api/graph',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'flashcard',phrase:card.jp,reading:card.reading,meaning:card.en,situation:active.label})});const data=await response.json();if(!response.ok)throw new Error(data.error);setSavedCards([...savedCards,card.jp]);setSaved(saved+1);setGraph(data.nodes)}catch(e:any){setError(e.message||'Could not save flashcard')}}
 return <main>
  <nav><div className="brand"><span className="brandMark">日</span><span>Nihongo <b>Lens</b></span><em>LIVE</em></div><div className="navRight"><span className="dot"/>Tokyo · {now}<button className="saved">Phrasebook <strong>{saved}</strong></button></div></nav>
  <section className="hero"><div className="eyebrow">REAL-TIME LANGUAGE COMPANION</div><h1>Understand Japan.<br/><i>Learn as you live.</i></h1><p>Instant translation with the context and Japanese you’ll need next time.</p></section>
  <section className="workspace"><div className="scenarioBar"><span>TRY A REAL-LIFE MOMENT</span><div>{scenes.map((s,i)=><button key={s.label} onClick={()=>choose(i)} className={selected===i?'active':''}><b>{s.icon}</b>{s.label}</button>)}</div></div>
   <div className="panels"><article className="inputPanel"><header><div><span>日本語</span><small>Japanese input</small></div><span className="secure">● SHISA SPEECH API</span></header><textarea aria-label="Japanese to translate" value={input} onChange={e=>setInput(e.target.value)} placeholder="Speak or type Japanese…"/><div className="reading">{listening?'Recording — tap Stop when finished':show?active.romaji:'Understanding Japanese…'}</div><footer><button className={`mic ${listening?'recording':''}`} onClick={listen}><span>{listening?'■':'●'}</span>{listening?'Stop & transcribe':'Record Japanese'}</button><button className="translate" onClick={()=>translate()}>Translate <span>→</span></button></footer></article>
   <article className="outputPanel"><header><div><span>EN</span><small>Natural English</small></div><span className="powered">POWERED BY <b>SHISA.AI</b></span></header>{loading?<div className="thinking"><span/><span/><span/> Understanding context…</div>:show&&<><p className="translationText">{output}</p><div className="context"><span>◎</span><div><b>Good to know</b><p>{active.context}</p></div></div></>}</article></div>
   {error&&<div className="errorBanner">{error}</div>}
   {show&&!loading&&<aside className="learnCard"><div className="learnLabel"><span>今日の日本語</span><small>LEARN FROM THIS MOMENT</small></div><div className="phrase"><strong>{active.phrase}</strong><span>{active.phraseR}</span></div><p>{active.meaning}</p><div className="learnActions"><button onClick={speak}>▶ Hear it</button><button onClick={savePhrase}>＋ Save</button></div></aside>}
   {graph&&<aside className="graphCard"><div><b>KNOWLEDGE GRAPH UPDATED</b><span>Powered by Neo4j</span></div><div className="graphFlow">{graph.map((node,i)=><span key={node}>{i>0&&<i>—</i>}<b className={`node n${i}`}>{node}</b></span>)}</div></aside>}
   {show&&!loading&&<section className="flashSection"><header><div><span>復習</span><div><b>Essential flashcards</b><small>Tap a card to reveal its meaning</small></div></div><em>{vocabulary[selected].length} KEY WORDS</em></header><div className="flashGrid">{vocabulary[selected].map((card,i)=>{const isFlipped=flipped===i,isSaved=savedCards.includes(card.jp);return <article key={card.jp} className={`flashCard ${isFlipped?'flipped':''}`} onClick={()=>setFlipped(isFlipped?null:i)}><div className="cardTop"><span>{i+1}</span><small>{isFlipped?'ENGLISH':'日本語'}</small></div><div className="cardWord"><strong>{isFlipped?card.en:card.jp}</strong><span>{isFlipped?'Meaning':card.reading}</span></div><button disabled={isSaved} onClick={e=>{e.stopPropagation();saveCard(card)}}>{isSaved?'✓ Stored in Neo4j':'＋ Save to Neo4j'}</button></article>})}</div></section>}
  </section><footer className="pageFooter"><span>Built for life in Japan</span><span>Translation gets you through today. Learning helps you belong tomorrow.</span></footer>
 </main>
}
